config/routes.rb
Rails.application.routes.draw do
 

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => "users#new"
  get 'general_english' => 'static_pages#GE'
  
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => "sessions#destroy"
  resources :exams do 
    resources :questions do 
      resources :choices
    end
  end
  get 'result' => 'exams#result'
  get 'answer' => 'exams#answer'
  #resources :questions do 
      #resources :choices
  #end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  validates :question_id, presence: true
  validates :content, length: { maximum: 140 }
  validates :is_correct, presence: true
end

app/models/exam.rb
class Exam < ApplicationRecord
	has_many :questions
	has_many :test_details
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :choices
	belongs_to :exam

	def feed
		Choice.where("is_correct = ? ", 1)
	end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  has_many :test_details
end

app/models/test_detail.rb
class TestDetail < ApplicationRecord
  belongs_to :test
  belongs_to :exam
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sentitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/Icon-user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :tests
	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
  	SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent seesions
  def remember 
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the givien token matches the digest.
  def authenticated?(remember_token) 
  	return false if remember_digest.nil?
  	 BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forget a user
  def forget
  	update_attribute(:remember_digest, nil)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ExamsHelper
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
	before_action :find_question
	before_action :find_exam
	def new 
		@choice = Choice.new
	end

	def create
		@choice = Choice.new(choice_params)
		@choice.question_id = @question.id
		if @choice.save 
			flash[:success] = "Choice added"
			redirect_to new_exam_question_choice_path(@exam, @question)
		else
			render 'new'
		end

	end

	private

		def choice_params
			params.require(:choice).permit(:content, :is_correct)
		end

		def find_question
			@question = Question.find(params[:question_id])
		end

		def find_exam
			@exam = Exam.find(params[:exam_id])
		end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	def new
		@exam = Exam.new
	end

	def show
		@exam = Exam.find(params[:id])
	end

	def index 
		@exams = Exam.all
	end

	def create
		@exam = Exam.new(exam_params)
		if @exam.save
			flash[:success] = "Exeam created!"
			redirect_to new_exam_question_path(@exam)
		else
			render 'new'

		end


	end

	def edit

	end

	private

		def exam_params
			params.require(:exam).permit(:name, :time)
		end

		









end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :find_exam
	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		@question.exam_id = @exam.id
		if @question.save
			flash[:success] = "Question added"
			redirect_to new_exam_question_choice_path(@exam, @question)
		else
			render 'new'
		end

	end


	private 

		def find_exam
			@exam = Exam.find(params[:exam_id])
		end

		def question_params
			params.require(:question).permit(:content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_or(user)
  	else
  		flash.now[:danger] = "Invalid Email or Password"
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end

	def contact
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  end
  def create 
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
    	flash[:success] = "Sign up successful"
    	redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = "Your Profile is updated."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end


  private
  	def user_params 
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  	end

    

    # Checking user logged in or not
    def logged_in_user 
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = "")
		base_title = "Multiple-Choice English"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper

	#def result(exam)
		#session[:exam_id] = exam.id
	#end

	
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user) 
		session[:user_id] = user.id
	end

	def remember(user) 
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in(user)
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end


	def log_out
		forget(current_user)
		session.delete(:user_id)
		current_user = nil
	end

	def current_user?(user)
		user == current_user
	end

	def store_location 
		session[:forwarding_url] = request.url if request.get
	end

	def redirect_back_or(default)
		redirect_to(session[:forwading_url] || default)
		session.delete(:forwarding_url)
	end

	def answer 
		Choice.where("is_correct = ?", 1)
	end

	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/choices/new.html.erb
<% provide(:title, "Adding Choices") %>
<h1 class="center">Adding Choices </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">  
			<%= form_for([@exam, @question, @question.choices.build]) do |f| %>
			
				<%= f.label :content %>
				<%= f.text_field :content, class: "form-control"%>

				<%= f.label :is_correct %>
				<%= f.number_field :is_correct, class: "form-control", placeholder: "1 for True or 0 for False..." %>

				
				<br>
				<%= f.submit "Adding Choices", class: "btn btn-primary" %>

			<% end %>

			<%= link_to "Create New Question", new_exam_question_path(@exam) %>
	</div>
</div>

app/views/exams/answer.html.erb
<% provide(:title, "Answer") %>
<h1 class="center">Answer</h1>
<% @exam = Exam.find_by(id: session[:exam_id]) %>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<ol class="background_exam">
			<br><br>
			<% @exam.questions.each do |question| %>
				<li><b><%= question.content %></b></li>
				<ul class="none_style">
						<% question.choices.each do |answer| %>
							<% if answer.is_correct == 1 %>
								<li><span class="choice"><%= answer.content %></span></li>	
							<% end %>
						<% end %>					
				</ul>
				<br>
			<% end %>
		</ol>
	</div>
</div>

app/views/exams/index.html.erb
<% provide(:title, "Exams") %>
<h1 class="center">Exams</h1>

<section id="all_exams">
	<ul>
		<% @exams.each do |exam| %>
		<li>
			<a href="/exams/<%= exam.id %>">
				<p><b><%= exam.name %></b></p>
			</a>
			<p>Time: <%= exam.time %> minutes.</p>
		</li>
		<% end %>
		
	</ul>

</section>

app/views/exams/new.html.erb
<% provide(:title, "New Exam") %>
<h1 class="center">Create Exam</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@exam) do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :time %>
			<%= f.number_field :time, class: "form-control" %>
			<br>
			<%= f.submit "Create Exam", class: "btn btn-primary" %>

		<% end %>

	</div>
</div>

app/views/exams/result.html.erb
<% provide(:title, "Result") %>
<% @exam = Exam.find_by(id: session[:exam_id]) %>
<h1 class="center">Your Result</h1>
<section class="result">
	<h3><%= @exam.name %></h3>
	<p>Time: <%= @exam.time %> minutes</p>
	<p>Your Score: <%= Random.rand(1..@exam.questions.count) %> / <%= @exam.questions.count %></p>
</section><br>
<div class="row">
	<div class="col-md-2 col-md-offset-5">
		<%= button_to "Exam's Answer", answer_path, method: :get, class: "btn btn-primary" %>
	</div> 
</div>

app/views/exams/show.html.erb
<% provide(:title,  @exam.name ) %>
<h1 class="center"><%= @exam.name %></h1>

<%# user = User.find_by(session[:user_id]) %>
<%# exam = Exam.find(params[:id])  %>
<% @test = current_user.tests.build(date_test: "nil", user_id: current_user.id) %>

<% @test_detail = @test.test_details.build(test_id: @test.id, exam_id: @exam.id, time_start: "nil", time_end: "nil")  %>
	
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<ol class="background_exam">
			<br><br>
			<% @exam.questions.each do |question| %>
				<li><b><%= question.content %></b></li>
				<ul class="none_style">
					<% question.choices.each do |choice| %>
						<% content = choice.content %>
						<li><%= radio_button_tag "choice #{ choice.question_id }", :content %><span class="choice"><%= content %></span></li>						
					<% end %>
				</ul>
				<br>
			<% end %>
		</ol>
		<% session[:exam_id] = @exam.id %>
		<%= button_to "Done", result_path, method: :get, class: "btn btn-primary" %>
		<%#= button_to "Adding question", new_exam_question_path(@exam) %>
	</div>
</div>

app/views/questions/new.html.erb
<% provide(:title, "Adding Question") %>
<h1 class="center">Adding Question </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for([@exam, @exam.questions.build]) do |f| %>
			<%= f.label :content %>
			<%= f.text_field :content, class: "form-control" %>
			<br>
			<%= f.submit "Adding Question", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/static_pages/GE.html.erb
<% provide(:title, "General English") %>
<h1 class="center">General English</h1>

<% @test = current_user.tests.build %>
<%  @test_detail = @test.test_details.build  %>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<% exam = Exam.find(1) %>
		<ol>
			<% exam.questions.each do |question| %>
				<li><%= question.content %></li>
				<ul class="none_style">
					<% question.choices.each do |choice| %>
						<% content = choice.content %>

						<li><%= radio_button_tag "choice #{ choice.question_id }", :content %><span class="choice"><%= content %></span></li>
						
						
					<% end %>
				</ul>
				<br>
			<% end %>
		</ol>
		<%= button_to "Done", result_path, method: :get, class: "btn btn-primary" %>

	</div>



</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<p></p>

app/views/static_pages/exams.html.erb
<% provide(:title, "Exams") %>
<h1 class="center">Exams</h1>

<section id="all_exams">
	<ul>
		<li>
			<a href="/general_english">
				<p>General English</p>
			</a>
			<p>Time: 90 minutes.</p>
		</li>
		<li style="background-color: blue;">
			<a href="/">
				<p>General English</p>
			</a>
			<p>Time: 90 minutes.</p>
		</li>
		<li style="background-color: red;">
			<a href="/">
				<p>General English</p>
			</a>
			<p>Time: 90 minutes.</p>
		</li>
		<br><br>
		<li style="background-color: green;">
			<a href="/">
				<p>General Engslish</p>
			</a>
			<p>Time: 90 minutes.</p>
		</li>
		<li style="background-color: yellow;">
			<a href="/">
				<p>General English</p>
			</a>
			<p>Time: 90 minutes.</p>
		</li>
	</ul>

</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<section class="intro">
	<div class="inner">
		<div class="content">
			<h1>Welcome to English Exams</h1>
			<a href="/signup"><button class="btn btn-primary">Sign Up Now!</button></a>
				
		</div>	
	</div>
</section>

app/views/static_pages/result.html.erb
<% provide(:title, "Result") %>

<h1 class="center">Your Result</h1>
<section class="result" >
	<h3></h3>

</section>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1 class="center">Update your profile</h1>

		<%= form_for(@user) do |f| %>
			<aside class="sidebar" >
				<div class="avatar">
					<%= image_tag @user.avatar, class: "user_avatar" %>
				</div>
				<p class="user_name"><%= @user.name %></p>
				<p class="choose_file"><%= f.file_field :avatar, accept: 'image/jpeg, image/gif, image/png, image/jpg' %></p>
			</aside>
			<div class="user_content">
				<%= render 'shared/error_messages' %>

			      <%= f.label :name %>
			      <%= f.text_field :name, class: 'form-control' %>

			      <%= f.label :email %>
			      <%= f.email_field :email, class: 'form-control' %>

			      <%= f.label :password %>
			      <%= f.password_field :password, class: 'form-control' %>

			      <%= f.label :password_confirmation, "Confirmation" %>
			      <%= f.password_field :password_confirmation, class: 'form-control' %>

				<br>
				<%= f.submit "Update your profile", class: "btn btn-primary" %>

			</div>
		<% end %>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1 class="center">All Users</h1>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<ul id="index users">
			<% @users.each do |user| %>
			<li>
				<%= image_tag user.avatar, class: "users" %>
				<span><%= link_to user.name, user_path(user) %></span>
				<br><br>
				<div class="border" ></div>
			</li>
			<% end %>
		</ul>


	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1 class="center">Sign Up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control"%>

			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
			<br>

			<%= f.submit "Create your account", class: "btn btn-primary" %>

		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<aside class="sidebar" >
	<h3 style="text-align: center;">Avatar</h3>
	<div class="avatar">
		<%= image_tag @user.avatar, class: "user_avatar" %>
	</div>
	<p class="user_name"><%= @user.name %></p>
</aside>



<section class="user_content">
	<h3>Exams( <%= Exam.count %> )</h3>
	<% @user.tests.each do |u_test| %>
		<% u_test.test_details.each do |test_detail| %>
			<% @exam = Exam.find_by(id: test_detail.exam_id) %>
			<div class="exam-style"></div>
			<ul>
				
				<li><p>Id: <%= test_detail.exam_id %></p></li>
				<li><p>Name: <%= @exam.name %></p></li>
				<li><p>Time: <%= @exam.time %> minutes</p></li>
				
			</ul>
			<div class="border"></div>
			<!--<div class="divider"></div>-->
		<% end %>
	<% end %>
</section>